### PR TITLE
Manual merge from anton-zolotarev:master

### PR DESCRIPTION
**Pull request by DmytroKorniienko**
Ack / Disconnect bugfix (server will be more stable on F5/Ctrl+F5)

### CODE REVIEW

**Comment by lorol** [comment]
Hi Dmytro,
Thank you for considering and developing on my fork! I will review the proposed changes when I have more time.

**Comment by lorol** [comment]
Hi again Dmytro,
Great work!
I believe you tested Ace if it takes all tricky links to function properly js css ...
Can you make edit.htm choice in FS vs.previous embedded way selectable by #define in code? So we can compile either way and compare resources and performance.
Also my extra scripts will need some adjustment for either choice , but this is straightforward.

**Comment by lorol** [comment]
Merge done via GitHub web interface

**Comment by DmytroKorniienko** [comment]
> Hi again Dmytro,
> Great work!
> I believe you tested Ace if it takes all tricky links to function properly js css ...
> Can you make edit.htm choice in FS vs.previous embedded way selectable by #define in code? So we can compile either way and compare resources and performance.
> Also my extra scripts will need some adjustment for either choice , but this is straightforward.

Hello lorol. I will review this part again later. Unfortunately I will be extremely busy in this week. As I remember in some cases highlight of code may be lost and will be recovered after moving to subfolders... There are bug somewhere, but not critical since edit work as expected.

**Pull request merged**
